#!/usr/bin/env ruby

require 'aws-sdk'
require 'base64'
require 'encryptor'
require 'json'
require_relative 'lib/kms.rb'
require_relative 'lib/s3.rb'
require_relative 'lib/dbb.rb'

bucket = ''
table = ''
file = ARGV[1]
key = ARGV[1]
value = ARGV[2]

kms = Kms.new
s3 = S3Kms.new(bucket)
ddb = DdbKms.new(table)

case ARGV[0]
when 'encrypt'
  puts kms.encrypt(file)
when 'decrypt'
  puts kms.decrypt(file)
when 'puts3'
  s3.puts3(file)
when 'gets3'
  s3.gets3(file)
when 'updates3'
  s3.updates3(file)
when 'deletes3'
  s3.deletes3(file)
when 'lists3'
  s3.lists3
when 'putdb'
  ddb.putdb(key, value)
when 'getdb'
  puts ddb.getdb(key)
when 'decryptdb'
  ddb.decryptdb(key)
when 'listdb'
  ddb.listdb
when 'deletedb'
  ddb.deletedb(key)
else
  STDOUT.puts <<-EOF
  Usage: #{$PROGRAM_NAME} command [arguments...]
    Commands:
      encrypt - creates encrypted data from a file
      decrypt - decrypts a file

      puts3 - stores file to an s3 bucket
      gets3 - retrieves file from an s3 bucket
      updates3 - updates a file stored in s3
      deletes3 - deletes a file from an s3 bucket
      lists3 - lists all files stored in an s3 bucket

      putdb - stores or updates a key and encrypted value in DynamoDB
      getdb - retrieves encrypted stored value for a given key from DynamoDB
      decryptdb - retrieves stored value from DynamoDB and returns it decrypted
      deletedb - deletes a stored key/value pair in Dynamodb
      listdb - lists all keys stored in Dynamodb

    Examples:
      #{$PROGRAM_NAME} encrypt unencrypted_file > encrypted_file
      #{$PROGRAM_NAME} decrypt encrypted_file
      #{$PROGRAM_NAME} decrypt encrypted_file > unencrypted_file

      #{$PROGRAM_NAME} puts3 file
      #{$PROGRAM_NAME} gets3 file
      #{$PROGRAM_NAME} updates3 file
      #{$PROGRAM_NAME} deletes3 file
      #{$PROGRAM_NAME} lists3

      #{$PROGRAM_NAME} putdb key_name 'a secret here'
      #{$PROGRAM_NAME} getdb key_name > filename
      #{$PROGRAM_NAME} decryptdb key_name
      #{$PROGRAM_NAME} deletedb key_name
      #{$PROGRAM_NAME} listdb
  EOF
end
